# Generated by Django 5.2.4 on 2025-09-02 00:44

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('profesor', models.CharField(max_length=100)),
                ('imagen_horario', models.FileField(blank=True, null=True, upload_to=core.models.curso_horario_upload_to)),
                ('cupo_minimo', models.PositiveIntegerField(default=1)),
                ('cupo_maximo', models.PositiveIntegerField(default=30)),
                ('fecha_limite', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ALUMNO', 'Alumno'), ('STAF', 'Staff'), ('ADMIN', 'Admin')], default='ALUMNO', max_length=10)),
                ('must_change_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('identidad', models.FileField(blank=True, null=True, upload_to=core.models.alumno_identidad_upload_to)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('faltante', 'Faltante'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('voucher', models.FileField(blank=True, null=True, upload_to=core.models.voucher_upload_to)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_faltante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to=core.models.calificacion_file_upload_to)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(through='core.Inscripcion', to='core.curso'),
        ),
    ]
