# Generated by Django 5.2.4 on 2025-09-07 03:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor'), ('STAF', 'Staff'), ('ADMIN', 'Admin')], default='ALUMNO', max_length=10),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.FileField(blank=True, help_text='Documentos subidos por el profesor', null=True, upload_to=core.models.profesor_documento_upload_to)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.profesor'),
        ),
    ]
